tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/6.2.0/types.yaml
  - plugin:cloudify-terraform-plugin
  - plugin:cloudify-ansible-plugin

node_templates:
  vm:
    type: cloudify.nodes.terraform.Module
    properties:
      resource_config:
        source:
          location: templates/vm.zip
        variables:
          access_key: { get_secret: aws_access_key_id }
          secret_key: { get_secret: aws_secret_access_key }
          aws_region: { get_input: [resource_config, aws_region_name] }
          instance_type: { get_input: [resource_config, instance_type] }
          key_name: { get_attribute: [vpc, outputs, key_name, value] }
          security_group_id: { get_attribute: [vpc, outputs, security_group_id, value] }
          subnet_id: { get_attribute: [vpc, outputs, subnet_id, value] }
    relationships:
      - type: cloudify.terraform.relationships.run_on_host
        target: terraform
      - type: cloudify.relationships.connected_to
        target: vpc

capabilities:
  ip_address:
    value: { get_attribute: [vm, outputs, ip, value]}