update-aws-deployment:
  image: jrzeszutek/cfyci:6.2.0
  variables:
    GIT_CHECKOUT: "true"
    INPUTS_FILE: "inputs/inputs-aws.yaml"
    SKIP_INSTALL: "false"
    SKIP_UNINSTALL: "false"
    SKIP_REINSTALL: "false"
    INSTALL_FIRST: "false"
    OUTPUTS_FILE: "-"
    DELETE_OLD_BLUEPRINT: "false"
    LABELS: "-"
  script:
    - cfyci install-or-update --name $AWS_EAAS_DEPLOYMENT_ID --blueprint-id $EAAS_BLUEPRINT_ID --delete-old-blueprint $DELETE_OLD_BLUEPRINT --inputs-file $INPUTS_FILE --labels $LABELS --skip-install $SKIP_INSTALL --skip-uninstall $SKIP_UNINSTALL --skip-reinstall $SKIP_REINSTALL --install-first $INSTALL_FIRST --outputs-file $OUTPUTS_FILE
  tags:
    - docker
      
update-gcp-deployment:
  image: jrzeszutek/cfyci:6.2.0
  variables:
    GIT_CHECKOUT: "true"
    INPUTS_FILE: "inputs/inputs-gcp.yaml"
    SKIP_INSTALL: "false"
    SKIP_UNINSTALL: "false"
    SKIP_REINSTALL: "false"
    INSTALL_FIRST: "false"
    OUTPUTS_FILE: "-"
    DELETE_OLD_BLUEPRINT: "false"
    LABELS: "-"
  script:
    - cfyci install-or-update --name $GCP_EAAS_DEPLOYMENT_ID --blueprint-id $EAAS_BLUEPRINT_ID --delete-old-blueprint $DELETE_OLD_BLUEPRINT --inputs-file $INPUTS_FILE --labels $LABELS --skip-install $SKIP_INSTALL --skip-uninstall $SKIP_UNINSTALL --skip-reinstall $SKIP_REINSTALL --install-first $INSTALL_FIRST --outputs-file $OUTPUTS_FILE
  tags:
    - docker